import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <head>
        <title>Wenzhou-Kean University Student Clubs</title>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-gray-100">
        <header className="bg-gray-800 text-white p-4 text-center">
          <h1 className="text-2xl">Wenzhou-Kean University Student Clubs</h1>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
